language: scala
script:
  - set -e
  - sbt scalafmtTest
  - sbt chromeUnpackedFast
  - sbt chromeUnpackedOpt
  - sbt chromePackage
jdk:
- oraclejdk8
# http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/
    - $HOME/.coursier/cache
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
notifications:
  email:
    on_success: never
    on_failure: always
